/* Generated By:JavaCC: Do not edit this line. KCAsmConstants.java */
public interface KCAsmConstants {

  int EOF = 0;
  int CR = 3;
  int EOL = 4;
  int WORD = 5;
  int PWORD = 6;
  int BINARY = 7;
  int OCTAL = 8;
  int DECIMAL = 9;
  int HEXADECIMAL = 10;
  int ASCII = 11;
  int LABEL = 12;
  int SEMICOLON = 13;
  int COMMENT = 14;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<CR>",
    "<EOL>",
    "<WORD>",
    "<PWORD>",
    "<BINARY>",
    "<OCTAL>",
    "<DECIMAL>",
    "<HEXADECIMAL>",
    "<ASCII>",
    "<LABEL>",
    "\";\"",
    "<COMMENT>",
    "\",\"",
  };

}
